server.port=8080
spring.datasource.url=jdbc:postgresql://aws-1-ap-southeast-2.pooler.supabase.com:5432/postgres?sslmode=require&prepareThreshold=0
spring.datasource.username=postgres.fqwckhcouilwteejfnfk
spring.datasource.password=rentuma143562
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.connection-init-sql=SELECT 1
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.boot.allow_jdbc_metadata_access=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
app.jwt.secret=eN34GVu64CUvrVqsJgununf8NR7aHK6lxutvqFmqa3k=
app.jwt.expiration-ms=86400000
app.jwt.refresh-expiration-ms=604800000
app.institutional.domain=cit.edu
app.supabase.url=https://fqwckhcouilwteejfnfk.supabase.co
app.supabase.anon-key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZxd2NraGNvdWlsd3RlZWpmbmZrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI4MTM5MjIsImV4cCI6MjA4ODM4OTkyMn0.pSvcyAuOn0j9xXHPg_BXZHiTyXS3TJ0QQ_SemC-m06w
spring.security.oauth2.client.registration.google.client-id=428918354170-05e2q5d7l3uvbqeqngtje2fibcnr5kap.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=openid,profile,email
spring.security.oauth2.client.provider.google.issuer-uri=https://accounts.google.com